name: CI-CD
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: 현재 브랜치로 체크아웃
        uses: actions/checkout@v4

      - name: PNPM 셋업
        uses: pnpm/action-setup@v4

      - name: Node 환경 셋업 및 PNPM 캐싱
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: 환경 변수 주입
        run: echo "${{ secrets.ENV }}" > .env

      - name: 패키지 의존성 설치
        run: pnpm install
      
      - name: TypeScript 타입 체크
        run: pnpm exec tsc -b

      - name: 코드 정적 분석
        run: pnpm lint

      - name: Chromatic으로 Storybook 테스트 및 배포
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: 프로젝트 빌드
        run: pnpm build

      - name: AWS Credentials 설정
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3에 배포
        if: github.event_name == 'push'
        run: |
          aws s3 sync \
            --region ${{ secrets.AWS_REGION }} \
            dist s3://${{ secrets.AWS_S3_BUCKET_NAME }} \
            --delete

      - name: CloudFront 캐시 무효화
        if: github.event_name == 'push'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
